### ISSUE TITLE
string.h not found

### ISSUE THREAD

**Issue by grigohas** [aitesam961/ara-build-playground#1]
hello i followed your work flow but when i am trying to do make bin/hello_world i get an error that string.h file not found

**Comment by aitesam961** [comment]
I think that mean some missing lib. I need to check which one but did you
install the packages in the first step?

**Comment by grigohas** [comment]
yeah i installed everything. when i installed ara on ubuntu 24.04 i didnt have that problem

**Comment by aitesam961** [comment]
Below are some fixes I can suggest

1- Run`make all ` in the root of project
2- Apply the modification for Verilator in `makefile` as suggested in the readme (CLANG variable replacement) and run `make verilator`
3- Make sure `make checkout` , `make update` and `make apply-patches`  are already executed in /ara/hardware.

Share the results or terminal log for any further errors

**Comment by aitesam961** [comment]
> yeah i installed everything. when i installed ara on ubuntu 24.04 i didnt have that problem

Were you able to run bender installation on 24.04?
I believe its not supported on 24. I tried on 24 but had multiple problems. Reverted to 22 LTS
Check https://github.com/pulp-platform/bender/pull/176

**Comment by grigohas** [comment]
yeah i did that and everything run properly

**Comment by aitesam961** [comment]
Well then I suggest continuing with 24 if that works for you.
